### ISSUE TITLE
The android app crashes

### ISSUE THREAD

**Issue by PranavGandhi** [mdietrichstein/yolo-tiny-v1-mobile#7]
java.lang.RuntimeException: Failed to load model from 'file:///android_asset/optimized_yolo.pb'
![error](https://user-images.githubusercontent.com/26665227/39445511-d97f9df4-4cd8-11e8-92fa-cb59e618102f.PNG)

**Comment by mdietrichstein** [comment]
The error shows that the android app is unable to deserialize the `optimized_yolo.pb` model, because of an unsupported attribute (`dilations`). I guess the reason for that problem is that you have used one version of tensorflow to generate the model and another (different) version to load the model on Android.

The code in this repository has been tested with Tensorflow 1.2.

**Comment by PranavGandhi** [comment]
Thank you
